---

  - name: restart aide
    service:
      name: aide
      state: restarted
    changed_when: False
    ignore_errors: True

  - name: restart ssh
    service:
      name: ssh
      state: restarted
    changed_when: False
    ignore_errors: True
